### ISSUE TITLE
Gas cost design

### ISSUE THREAD

**Issue by spennyp** [papercliplabs/compound-info#79]
How does the gas look for each market, or do we keep the modal?

**Comment by alexreyes** [comment]
The real time cost on the site is super helpful. One piece of feedback I have is that it's a bit confusing to always have gas costs for USDC. Maybe it would make more sense to change USDC to ERC-20? 

Also, a supply/borrow gas modal for ETH would be helpful too, since the costs between ETH and the rest of the coins would differ
